### ISSUE TITLE
As a guest, I can register as a user by entering my email, password, and telephone number.

### ISSUE THREAD

**Issue by case-eee** [case-eee/kackle#4]

**Comment by s-espinosa** [comment]
@case-eee Related to #5 and #6: Do we need emails/passwords? I'm wondering if we just ask for a phone number to activate and then provide a way to deactivate by just entering the phone number where you want messages to stop.

If we do want email/password, do you think BCrypt is sufficient? I don't necessarily see an advantage to Devise for something like this, but haven't really played with it and could be missing something.

**Comment by case-eee** [comment]
@s-espinosa i was thinking just bcrypt for now. if we add the functionality for user's to potentially change the timing of their daily text, then i see value in having an email/password combination for them to manage their account. we could even add the functionality (later) for them to suspend their service.

i agree though - maybe emails and passwords aren't MVP? i'd also be hesitant to just allow users to put in their phone number to cancel - that'd mean anyone could put in their phone number and we wouldn't be sure if it's actually them

thoughts?

**Comment by s-espinosa** [comment]
@case-eee Ha! Hadn't thought about someone else cancelling for me.

I also hadn't thought about how this might tie to the timing of their text. Think you're probably right that it makes sense to have a user log in to manage that functionality.
